apiVersion: v1
kind: Namespace
metadata:
  name: f6sny-legacy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f6sny-api-v3
  namespace: f6sny-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f6sny-api-v3
      component: backend
  template:
    metadata:
      labels:
        app: f6sny-api-v3
        component: backend
    spec:
      containers:
      - name: f6sny-api-v3
        image: ghcr.io/f6sny/api.f6sny.com@sha256:f6c3d76e6257b7dd11affee2757ed3715c0f899aab2c8f78aa20c94099680bb6
        ports:
          - containerPort: 1337
        envFrom:
          - secretRef:
              name: f6sny-api-v3-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: f6sny-api-v3-secrets
  namespace: f6sny-legacy
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: f6sny-api-v3-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: f6sny_legacy 
        property: ADMIN_JWT_SECRET
    - secretKey: API_AUTH_URL
      remoteRef:
        key: f6sny_legacy
        property: API_AUTH_URL
    - secretKey: API_URL
      remoteRef:
        key: f6sny_legacy
        property: API_URL
    - secretKey: DATABASE_HOST
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_HOST
    - secretKey: DATABASE_NAME
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_NAME
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_PORT
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_PORT
    - secretKey: DATABASE_SSL
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_SSL
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_USERNAME
    - secretKey: HOST
      remoteRef:
        key: f6sny_legacy
        property: HOST
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: f6sny_legacy
        property: MEILI_MASTER_KEY
    - secretKey: NODE_ENV
      remoteRef:
        key: f6sny_legacy
        property: NODE_ENV
    - secretKey: NUXT_HOST
      remoteRef:
        key: f6sny_legacy
        property: NUXT_HOST
    - secretKey: NUXT_PORT
      remoteRef:
        key: f6sny_legacy
        property: NUXT_PORT
    - secretKey: PORT
      remoteRef:
        key: f6sny_legacy
        property: PORT
    - secretKey: PUBLIC_URL
      remoteRef:
        key: f6sny_legacy
        property: PUBLIC_URL
    - secretKey: URL
      remoteRef:
        key: f6sny_legacy
        property: URL
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f6sny-api-v3-ingress
  namespace: f6sny-legacy
  annotations:
    cert-manager.io/cluster-issuer: http01-clusterissuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - legacy-api.f6sny.com
      secretName: f6sny-api-v3-tls
  rules:
  - host: legacy-api.f6sny.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: f6sny-api-v3
              port:
                number: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: f6sny-api-v3
  namespace: f6sny-legacy
spec:
  selector:
    app: f6sny-api-v3
    component: backend
  ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f6sny-nuxt-frontend
  namespace: f6sny-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f6sny-nuxt-frontend
      component: frontend
  template:
    metadata:
      labels:
        app: f6sny-nuxt-frontend
        component: frontend
    spec:
      containers:
      - name: f6sny-nuxt-frontend
        image: ghcr.io/f6sny/www.f6sny.com@sha256:088d3ec47416b05c099abe1ab3d3523d78e477eb30da6881d61566c8fee05125
        ports:
          - containerPort: 5050
        envFrom:
          - secretRef:
              name: f6sny-nuxt-frontend-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: f6sny-nuxt-frontend-secrets
  namespace: f6sny-legacy
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: f6sny-nuxt-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: f6sny_legacy 
        property: ADMIN_JWT_SECRET
    - secretKey: API_AUTH_URL
      remoteRef:
        key: f6sny_legacy
        property: API_AUTH_URL
    - secretKey: API_URL
      remoteRef:
        key: f6sny_legacy
        property: API_URL
    - secretKey: DATABASE_HOST
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_HOST
    - secretKey: DATABASE_NAME
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_NAME
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_PORT
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_PORT
    - secretKey: DATABASE_SSL
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_SSL
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: f6sny_legacy
        property: DATABASE_USERNAME
    - secretKey: HOST
      remoteRef:
        key: f6sny_legacy
        property: HOST
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: f6sny_legacy
        property: MEILI_MASTER_KEY
    - secretKey: NODE_ENV
      remoteRef:
        key: f6sny_legacy
        property: NODE_ENV
    - secretKey: NUXT_HOST
      remoteRef:
        key: f6sny_legacy
        property: NUXT_HOST
    - secretKey: NUXT_PORT
      remoteRef:
        key: f6sny_legacy
        property: NUXT_PORT
    - secretKey: PORT
      remoteRef:
        key: f6sny_legacy
        property: PORT
    - secretKey: PUBLIC_URL
      remoteRef:
        key: f6sny_legacy
        property: PUBLIC_URL
    - secretKey: URL
      remoteRef:
        key: f6sny_legacy
        property: URL
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f6sny-nuxt-frontend-ingress
  namespace: f6sny-legacy
  annotations:
    cert-manager.io/cluster-issuer: http01-clusterissuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - legacy.f6sny.com
      secretName: f6sny-nuxt-frontend-tls
  rules:
  - host: legacy.f6sny.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: f6sny-nuxt-frontend
              port:
                number: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: f6sny-nuxt-frontend
  namespace: f6sny-legacy
spec:
  selector:
    app: f6sny-nuxt-frontend
    component: frontend
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  type: ClusterIP